name: SSH Access Through Cloudflare Tunnel

on:
  push:
    branches:
      - main

jobs:
  ssh_via_cloudflare:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          sudo chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Set up SSH key in ~/.ssh directory
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate SSH config with cloudflared
        env:
          TUNNEL_HOSTNAME: ${{secrets.SSH_HOST}}
        run: |
          # Use cloudflared to generate SSH config and append to ~/.ssh/config
          cloudflared access ssh-config --hostname $TUNNEL_HOSTNAME >> ~/.ssh/config

      - name: Test SSH connection haha
        env:
          SERVER_USER: ${{secrets.SSH_USER}}
          TUNNEL_HOSTNAME: ${{secrets.SSH_HOST}}
        run: |
          # Connect to the server through SSH using the Cloudflare tunnel
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$TUNNEL_HOSTNAME "echo 'SSH connection successful'"
