name: SSH Access Through Cloudflare Tunnel and Start Docker Container

on:
  push:
    branches:
      - main

jobs:
  ssh_and_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          sudo chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Start Docker Container on Remote Server
        env:
          SERVER_USER: ${{ secrets.SSH_USER }}
          TUNNEL_HOSTNAME: ${{ secrets.SSH_HOST }}
          DOCKER_IMAGE: your_docker_image_name # Replace with your Docker image name
        run: |
          # Start the Docker container remotely
          ssh -o StrictHostKeyChecking=no \
              -o "ProxyCommand=cloudflared access ssh --hostname %h" \
              $SERVER_USER@$TUNNEL_HOSTNAME "
                echo 'Starting Docker container on remote server...';
                docker container ls -a;
                docker container ls;"
